ALTER TABLE "GateRecord" ADD COLUMN IF NOT EXISTS "staffId" INTEGER REFERENCES "Staff"("id");
ALTER TABLE "GateRecord" ADD COLUMN IF NOT EXISTS "method" TEXT NOT NULL DEFAULT 'MANUAL';
ALTER TABLE "Staff" ADD COLUMN IF NOT EXISTS "attendanceCode" TEXT UNIQUE;
ALTER TYPE "GateRecordType" ADD VALUE IF NOT EXISTS 'ADMINISTRATIVO';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'PSICOLOGO';
CREATE TABLE IF NOT EXISTS "BiometricTemplate" (
  "id" SERIAL PRIMARY KEY,
  "template" TEXT NOT NULL,
  "deviceId" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "teacherId" INTEGER REFERENCES "Teacher"("id"),
  "staffId" INTEGER REFERENCES "Staff"("id")
);